-- 1. 랙 격자판 재고 데이터 테이블 생성
CREATE TABLE IF NOT EXISTS rack_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sheet_name TEXT NOT NULL,
  rack_row INT NOT NULL,
  rack_col INT NOT NULL,
  product_name TEXT,
  pallet_qty INT DEFAULT 0,
  box_qty INT DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  -- 동일한 시트, 행, 열의 데이터는 하나만 존재하도록 복합 유니크 제약 설정 (Upsert 지원용)
  CONSTRAINT unique_rack_cell UNIQUE (sheet_name, rack_row, rack_col)
);

-- 2. 제품 메타데이터 테이블 생성 (TOTAL 시트 집계용 정보)
CREATE TABLE IF NOT EXISTS product_metadata (
  product_name TEXT PRIMARY KEY,
  ipsuryang INT DEFAULT 0,
  box_danyi INT DEFAULT 0,
  janryang INT DEFAULT 0,
  chulgo INT DEFAULT 0,
  panmae_ilbo INT DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Row Level Security (RLS) 활성화 및 누구나 접근 가능한 Policy 설정 (초보자용/인프라 연동 최적화)
ALTER TABLE rack_inventory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read for rack_inventory" ON rack_inventory FOR SELECT USING (true);
CREATE POLICY "Allow public insert for rack_inventory" ON rack_inventory FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update for rack_inventory" ON rack_inventory FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete for rack_inventory" ON rack_inventory FOR DELETE USING (true);

ALTER TABLE product_metadata ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read for product_metadata" ON product_metadata FOR SELECT USING (true);
CREATE POLICY "Allow public insert for product_metadata" ON product_metadata FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update for product_metadata" ON product_metadata FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete for product_metadata" ON product_metadata FOR DELETE USING (true);

-- 4. 실시간 동기화(Realtime) 활성화
-- Supabase에서 Realtime 채널을 활성화하기 위해 publications 목록에 테이블 추가
alter publication supabase_realtime add table rack_inventory;
alter publication supabase_realtime add table product_metadata;
